//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace IOT.Demo.Umbraco.Models.CmsGenerated
{
	// Mixin Content Type with alias "conferenceSchedule"
	/// <summary>Conference Schedule</summary>
	public partial interface IConferenceSchedule : IPublishedContent
	{
		/// <summary>Conference End Date</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		DateTime ConferenceEndDate { get; }

		/// <summary>Conference Name Synonyms</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		IEnumerable<string> ConferenceNameSynonyms { get; }

		/// <summary>Conference Start Date</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		DateTime ConferenceStartDate { get; }

		/// <summary>Schedule</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		IEnumerable<ScheduleItem> Schedule { get; }
	}

	/// <summary>Conference Schedule</summary>
	[PublishedModel("conferenceSchedule")]
	public partial class ConferenceSchedule : PublishedContentModel, IConferenceSchedule
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "conferenceSchedule";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ConferenceSchedule, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public ConferenceSchedule(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Conference End Date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("conferenceEndDate")]
		public DateTime ConferenceEndDate => GetConferenceEndDate(this);

		/// <summary>Static getter for Conference End Date</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static DateTime GetConferenceEndDate(IConferenceSchedule that) => that.Value<DateTime>("conferenceEndDate");

		///<summary>
		/// Conference Name Synonyms: This will be used to match up on incoming slot values.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("conferenceNameSynonyms")]
		public IEnumerable<string> ConferenceNameSynonyms => GetConferenceNameSynonyms(this);

		/// <summary>Static getter for Conference Name Synonyms</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IEnumerable<string> GetConferenceNameSynonyms(IConferenceSchedule that) => that.Value<IEnumerable<string>>("conferenceNameSynonyms");

		///<summary>
		/// Conference Start Date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("conferenceStartDate")]
		public DateTime ConferenceStartDate => GetConferenceStartDate(this);

		/// <summary>Static getter for Conference Start Date</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static DateTime GetConferenceStartDate(IConferenceSchedule that) => that.Value<DateTime>("conferenceStartDate");

		///<summary>
		/// Schedule
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("schedule")]
		public IEnumerable<ScheduleItem> Schedule => GetSchedule(this);

		/// <summary>Static getter for Schedule</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IEnumerable<ScheduleItem> GetSchedule(IConferenceSchedule that) => that.Value<IEnumerable<ScheduleItem>>("schedule");
	}
}
